AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stock-market-etl-pipeline

  Sample SAM Template for stock-market-etl-pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.14
      Policies:
        - S3WritePolicy:
            BucketName: !Ref StockDataBucket
        - SSMParameterReadPolicy:
            ParameterName: alphavantage-api-key
      Architectures:
      - x86_64
      Events:
        DailyFetch:
          Type: Schedule
          Properties:
            Schedule: cron(30 23 * * ? *)
            Name: DailyStockFetchSchedule
            Description: Triggers stock data fetch once daily after the market closes
            Enabled: true
  StockDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "stock-market-etl-data-${AWS::AccountId}"
  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
